version: '3.3'

services:
  frappe:
    image: pipech/erpnext-docker-debian:v12-py3-latest
    deploy:
      # mode: global
      # restart_policy:
      #   condition: on-failure
      replicas: 1

    volumes:
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-logs-volumes:/home/frappe/bench/logs
    stdin_open: true
    tty: true
    env_file:
      - frappe_app.env
    command: ["/home/frappe/production_config/entrypoint_prd.sh"]
    labels:
      - "traefik.enable=false"
      # - "traefik.frontend.rule=Host:example1.com, example2.com" [Separate with comma]
      #- "traefik.frontend.rule=Host:example1.com"
      #- "traefik.port=80"
      #- "traefik.docker.network=traefik_proxy"
    networks:
      #- traefik_proxy
      #- frappe_db
      #- default
      - swarm-network

  redis-cache:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-cache-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    networks:
      #- default
      - swarm-network

  redis-queue:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-queue-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    networks:
      #- default
      - swarm-network

  redis-socketio:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-socketio-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]
    networks:
      #- default
      - swarm-network

volumes:
  frappe-sites-volumes:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4.1,addr=anqci.file.core.windows.net,nolock,soft,rw
      device: ":/anqci/prod-storage/erpnext/sites"
  frappe-logs-volumes:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4.1,addr=anqci.file.core.windows.net,nolock,soft,rw
      device: ":/anqci/prod-storage/erpnext/logs"

configs:
  redis-cache-conf:
    file: redis-conf/redis_cache.conf
  redis-queue-conf:
    file: redis-conf/redis_queue.conf
  redis-socketio-conf:
    file: redis-conf/redis_socketio.conf

#networks:
#  traefik_proxy:
#    external: true
#  frappe_db:
#    external: true
networks:
  swarm-network:
    external: true